### PR TITLE
Make it fit for ES 2.1

### PR DESCRIPTION
**Pull request by AndreKR**

### CODE REVIEW

**Comment by vhyza** [comment]
Thanks @AndreKR!

Unfortunately I have some problems with compiling this. It seems that `jlemmagen` repository https://mvn.datalan.sk/maven2/libs-snapshots-local/ is down. Author of `jlemmagen` project changed the repository to https://xmaven.datalan.sk/maven2/libs-snapshots-local. But this repository has HTTP basic auth. Is this the reason why you added commit d78755ddd31dc9e4b8bd2a8f92d1e61ff3927448?

Next problem is, that `jlemmagen` author [changed one method name](https://bitbucket.org/hlavki/jlemmagen/commits/04782dae2f5eb379a6a19bb9c067045618821395). So when this plugin is compiled against old build of `jlemmagen` everything works. But with new one it is broken.

I compiled new `jlemmagen` build, copied `jlemmagen-1.0-SNAPSHOT.jar` and `jlemmagen-lang-1.0-SNAPSHOT.jar` into `lib` directory, corrected method call, built and installed plugin using `elasticsearch 2.1` and everything seems ok, but I'd like to ask as non-java developer if it is ok when I push `jlemmagen-1.0-SNAPSHOT.jar` and `jlemmagen-lang-1.0-SNAPSHOT.jar` dependencies into `lib` directory as current code depends on new `jlemmagen` build? Or what are the best practices when some dependency repository is not reliable?

**Comment by AndreKR** [comment]
Yes, the reason for d78755d is that the jlemmagen dependency is down. So I just copied those two jars into the lib directory. We could push them as well.

I'm not a Java developer either, sorry. However, I think we should not have two incompatible jars around that have the same name - we (or rather the original author) should change the version number or add a suffix or something. Or we just use the old jars, without recompiling it... since the version number didn't increase, I guess we don't gain any new features?

**Comment by vhyza** [comment]
> However, I think we should not have two incompatible jars around that have the same name

I'm not sure what you mean. There is no `*.jar` currently in repository.


I compiled `*.jar` from new sources and there are couple of changes. For example [added support of persian language](https://bitbucket.org/hlavki/jlemmagen/commits/1d44920866e53fdc4d83b02546b285dd04276595) or [removed debug logging](https://bitbucket.org/hlavki/jlemmagen/commits/ee5e8e68d99345b48b09d3aa67d9fc297dc17395).

 So I think it is worth it to have plugin compiled with new `*.jar` dependencies. Because of that I suggest to push `*.jar` into `lib` directory in this repository. I have dependencies already compiled and following changes made so I could add it to PR and merge it.

Anyway, after those changes, everything works fine. Thank you!

**Comment by AndreKR** [comment]
Oh that debug logging, now that's a useful change, that annoyed the hell out of me. ;) Go ahead and push the new libraries.

**Comment by vhyza** [comment]
Exactly, same with me :)

**Pull request merged**
