### PR TITLE
Prepare plugin for Elasticsearch 8.8.1

### PR DESCRIPTION
**Pull request by dainiusjocas**
Just a dependency bump.

### CODE REVIEW

**Comment by KovacicB** [comment]
Is it possible to try and use v8.8.1 (this PR) locally and if yes - how? I can only fork source files, not built .jars.

**Comment by dainiusjocas** [comment]
> Is it possible to try and use v8.8.1 (this PR) locally and if yes - how? I can only fork source files, not built .jars.

The way I do it is:
 (1) clone the repo
 (2) mvn package
 (3) take the jar from target dir and use it to install into Elasticsearch
 (4) run Elasticsearch
 
 
So, If you want to try, you must build the jar of the plugin by yourself.

**Comment by KovacicB** [comment]
1) I have obtained the jars, zipped in the archive in the same way as official 8.6.1 release (a file named `elasticsearch-analysis-lemmagen-8.8.1-plugin.zip` containing `elasticsearch-analysis-lemmagen-8.8.1.jar, jlemmagen-1.0.jar, plugin-descriptor.properties, slf4j-api-1.6.2.jar, slf4j-simple-1.6.2.jar`
2) I have transferred the zip to docker container to `/usr/share/elasticsearch/config/elasticsearch-analysis-lemmagen-8.8.1-plugin.zip`
3) I run `./bin/elasticsearch-plugin install /usr/share/elasticsearch/config/elasticsearch-analysis-lemmagen-8.8.1-plugin.zip` but I get the following error: `ERROR: Unknown plugin /usr/share/elasticsearch/config/elasticsearch-analysis-lemmagen-8.8.1-plugin.zip`
Any solutions?

**Comment by KovacicB** [comment]
Great and it works! Thank you!

**Comment by vhyza** [comment]
Hi @dainiusjocas,

thank you for the PR. I'm sorry I didn't get back to you sooner. I'm quite swamped with other projects and as I do not use the plugin for years now, my motivation is not the strongest.

Anyway, I'd like to get back one day, but it will probably take some more time. I'm sorry about that.

**Pull request closed without merging**
